### ISSUE TITLE
Trial initial landing page design with Sass and FT components

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/tech-access#20]
- [x] Create basic landing page layout served via Handlebars
- [x] Trial using Sass with the landing/opening page(s)
- [x] Look to see if handlebars affects code coverage, and whether there is a way to either test or avoid this
