### ISSUE TITLE
"Epic": Plans for final few hours

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/tech-access#52]
The final stretch!

Presentation
- [ ] Contribute to readme
- [ ] Contribute gifs to readme
- [ ] Plan presentation!

Testing 
- [ ] See if we can improve our test coverage

Small changes
- [ ] Merge Kate's branch now that we've all checked and updated it
- [ ] Sangita to add her pre-sorting function
- [ ] Dom (and Kate?) to make some more minor changes (I am planning to have a go at preventing people from clicking "next" if they haven't selected anything)
