### ISSUE TITLE
Epic: Project/server set up (WIP)

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/tech-access#9]
- [x] File structure (can use ".gitkeep" files for empty folders)
- [x] Improve .gitignore (node, DS_Store, package-lock.json?)
- [x] Add documents folder with empty "design.md and database.md" files
- [x] dev dependencies (nodemon, eslint, supertest, jest)
- [x] project dependencies (express, pg-promise, env2, sequelize, querystring, express-handlebars, body-parser, serve-favicon)
- [x] Google eslint settings setup (previously planned to use FT)
- [x] Have the server display *something* at our route
- [x] Single test to say server running

Everyone:
- [x] Ensure our prettier (and ESLint) settings are in sync (decided to disable prettier in the end)
- [x] Install Sass on computers

**Comment by VirtualDOMinic** [comment]
Doing this as a group. Need to first decide on Jest vs tape/tap-spec/codecov

**Comment by VirtualDOMinic** [comment]
Will need to set up the jest code coverage report in our `.travis.yml`

**Comment by VirtualDOMinic** [comment]
All of us have disabled prettier in vscode. Please react with thumbs up to confirm! @MissArray @sunuwars @sbinlondon

**Comment by VirtualDOMinic** [comment]
All of us have installed Sass globally on our laptops. Please react with thumbs up to confirm!
